from classes import AssetInfo

DICT_ASSET_INFO = {    
'SLCE3':AssetInfo(name="SLCE3", ticker="SLCE3.SA", asset_class="Ação", stock_b3=True),
'SUZB3':AssetInfo(name="SUZB3", ticker="SUZB3.SA", asset_class="Ação", stock_b3=True),
'BBAS3':AssetInfo(name="BBAS3", ticker="BBAS3.SA", asset_class="Ação", stock_b3=True),
'ROMI3':AssetInfo(name="ROMI3", ticker="ROMI3.SA", asset_class="Ação", stock_b3=True),
'ITSA4':AssetInfo(name="ITSA4", ticker="ITSA4.SA", asset_class="Ação", stock_b3=True),
'CMIG4':AssetInfo(name="CMIG4", ticker="CMIG4.SA", asset_class="Ação", stock_b3=True),
'GGBR4':AssetInfo(name="GGBR4", ticker="GGBR4.SA", asset_class="Ação", stock_b3=True),
'BBDC4':AssetInfo(name="BBDC4", ticker="BBDC4.SA", asset_class="Ação", stock_b3=True),
'VALE3':AssetInfo(name="VALE3", ticker="VALE3.SA", asset_class="Ação", stock_b3=True),
'TRPL4':AssetInfo(name="TRPL4", ticker="TRPL4.SA", asset_class="Ação", stock_b3=True),
'CIEL3':AssetInfo(name="CIEL3", ticker="CIEL3.SA", asset_class="Ação", stock_b3=True),
'SAPR4':AssetInfo(name="SAPR4", ticker="SAPR4.SA", asset_class="Ação", stock_b3=True),
'PSSA3':AssetInfo(name="PSSA3", ticker="PSSA3.SA", asset_class="Ação", stock_b3=True),
'ALZR11':AssetInfo(name="ALZR11", ticker="ALZR11.SA",asset_class="FII", stock_b3=True),
'HGRU11':AssetInfo(name="HGRU11", ticker="HGRU11.SA",asset_class="FII", stock_b3=True),
'HSML11':AssetInfo(name="HSML11", ticker="HSML11.SA",asset_class="FII", stock_b3=True),
'HGPO11':AssetInfo(name="HGPO11", ticker="HGPO11.SA",asset_class="FII", stock_b3=True),
'HGLG11':AssetInfo(name="HGLG11", ticker="HGLG11.SA",asset_class="FII", stock_b3=True),
'BODB11':AssetInfo(name="BODB11", ticker="BODB11.SA",asset_class="FII", stock_b3=True),
'TRXF11':AssetInfo(name="TRXF11", ticker="TRXF11.SA",asset_class="FII", stock_b3=True),
'CLIN11':AssetInfo(name="CLIN11", ticker="CLIN11.SA",asset_class="FII", stock_b3=True),
'CPTI11':AssetInfo(name="CPTI11", ticker="CPTI11.SA",asset_class="FII", stock_b3=True),
'KNSC11':AssetInfo(name="KNSC11", ticker="KNSC11.SA",asset_class="FII", stock_b3=True),
'KNIP11':AssetInfo(name="KNIP11", ticker="KNIP11.SA",asset_class="FII", stock_b3=True),
'RBRR11':AssetInfo(name="RBRR11", ticker="RBRR11.SA",asset_class="FII", stock_b3=True),
'ALUG11':AssetInfo(name="ALUG11", ticker="ALUG11.SA",asset_class="FII", stock_b3=True),
'KORE11':AssetInfo(name="KORE11", ticker="KORE11.SA",asset_class="FII", stock_b3=True),
'HGRE11':AssetInfo(name="HGRE11", ticker="HGRE11.SA",asset_class="FII", stock_b3=True),
'RBVA11':AssetInfo(name="RBVA11", ticker="RBVA11.SA",asset_class="FII", stock_b3=True),
'KNCA11':AssetInfo(name="KNCA11", ticker="KNCA11.SA",asset_class="FII", stock_b3=True),
'BTCR11':AssetInfo(name="BTCR11", ticker="BTCI11.SA",asset_class="FII", stock_b3=True),
'JSRE11':AssetInfo(name="JSRE11", ticker="JSRE11.SA",asset_class="FII", stock_b3=True),
'CVBI11':AssetInfo(name="CVBI11", ticker="CVBI11.SA",asset_class="FII", stock_b3=True),
'BCRI11':AssetInfo(name="BCRI11", ticker="BCRI11.SA",asset_class="FII", stock_b3=True),
'GGRC11':AssetInfo(name="GGRC11", ticker="GGRC11.SA",asset_class="FII", stock_b3=True),
'HGCR11':AssetInfo(name="HGCR11", ticker="HGCR11.SA",asset_class="FII", stock_b3=True),
'KNCR11':AssetInfo(name="KNCR11", ticker="KNCR11.SA",asset_class="FII", stock_b3=True),
'SPXI11':AssetInfo(name="SPXI11", ticker="SPXI11.SA",asset_class="USD", stock_b3=True),
'BITH11':AssetInfo(name="BITH11", ticker="BITH11.SA",asset_class="USD", stock_b3=True),
'USDB11':AssetInfo(name="USDB11", ticker="USDB11.SA",asset_class="USD", stock_b3=True),
'LFTS11':AssetInfo(name="LFTS11", ticker="LFTS11.SA",asset_class="Tesouro",stock_b3=True),
'Selic 2026':AssetInfo(name="Selic 2026", ticker="Selic 2026", asset_class="Tesouro", bond=True),
'Selic 2029':AssetInfo(name="Selic 2029", ticker="Selic 2029", asset_class="Tesouro", bond=True),
'IPCA+ 2029':AssetInfo(name="IPCA+ 2029", ticker="IPCA+ 2029", asset_class="Tesouro", bond=True),
'IPCA+ 2045':AssetInfo(name="IPCA+ 2045", ticker="IPCA+ 2045", asset_class="Tesouro", bond=True),
'Prefixado 2029':AssetInfo(name="Prefixado 2029", ticker="Prefixado 2029",asset_class="Tesouro", bond=True),
'BIL':AssetInfo(name="BIL", ticker="BIL", asset_class="USD", stock_us=True),
'IBIT':AssetInfo(name="IBIT", ticker="IBIT", asset_class="USD", stock_us=True),
'TLT':AssetInfo(name="TLT", ticker="TLT", asset_class="USD", stock_us=True),
'SHY':AssetInfo(name="SHY", ticker="SHY", asset_class="USD", stock_us=True),
'IVV':AssetInfo(name="IVV", ticker="IVV", asset_class="USD", stock_us=True),
}